rpc:
  endpoints:
    - https://solana-rpc.publicnode.com
    - https://solana.drpc.org
    - https://solana.api.onfinality.io/public

ws:
  endpoints:
    - wss://solana-rpc.publicnode.com
    - wss://solana.drpc.org
    - wss://solana.api.onfinality.io/public

# https://swap.pump.fun/ — адреса контрактов токенов (mint)
pumpswap:
  mints:
    - "9FPRvikGKGR9VSV4g5Luw91iDtZEPihuNtKFQcnupump"

stream:
  commitment: processed
  reconnect_delay_ms: 2000
